#Login credentional
browser=chrome
Url=https://www.naukri.com/nlogin/login
email=manirathnam1794@gmail.com
password=123Mani@abc

#profile update


#Resumeheadline
resumeHeadline = my name is manirathnam K from chennai


#Employment
companyname = Toast
designation = QA Engineer
joinedyear = 2020
joinedmonth = Nov
skillused = Manual and Automation
noticeperiod = 30