testURL=https://www.saucedemo.com
chromeDriverPath=delayed
#platforms - local, remote
runPlatform=local
#available browsers - chrome, firefox, edge
browser=chrome
gridUrl=http://localhost:4444/wd/hub
amzTestUrl=https://www.amazon.in/
demoSauceUrl=https://www.saucedemo.com/