
browser=chrome
Url=https://www.demoblaze.com/
username=manirathnam K
password=123@123
logout=logout

catagories_xpath = "//a[contains(text(),'Phones')]";
product_linkText = "Samsung galaxy s6";
addToCart_linkText = "Add to cart";
cart_linkText = "Cart";
placeOrder_xpath = "//button[text()='Place Order']";


name_id = "name"
country_id = "country"
city_id = "city"
creditCard_id = "card"
month_id = "month"
year_id = "year"
purchase_xpath = "//button[contains(text(),'Purchase')]"


name = Manirathnam K
country = India
city = Chennai
card = Credit
month = DEC
year = 2025